### PR TITLE
Timeline Component

### PR DESCRIPTION
**Pull request by lohanidamodar**
I have created a timeline component, its simple, demo is below. I hope you guys will like it
deepin-screen-recorder_select area_20170814190641

Thank you

### CODE REVIEW

**Comment by D40723570** [comment]
Woah, such amazing component! Thank you so much for your contribution as always 🎉  🎉

**Comment by yannbf** [comment]
Woah, such amazing component! Thank you so much for your contribution as always 🎉 🎉

**Comment by miguelcarrascoq** [comment]
cool !

**Comment by corysmc** [comment]
Seriously beautiful! I want to build an app with a timeline just to use it! Great addition @lohanidamodar!

**Pull request merged**
