### PR TITLE
added team page

### PR DESCRIPTION
**Pull request by asabya**
A team members page showing team member images in ion-tab and displaying their info in another page.
team

### CODE REVIEW

**Comment by asabya** [comment]
Hi @yannbf, did you get any chance to review this? 
Thanks

**Comment by yannbf** [comment]
Hey @Sab94 ! I am terribly sorry for not having reviewed this PR. I've been away for quite a long time, now I am trying to catch up again. 

Great contribution, thanks a lot for that!

**Comment by yannbf** [comment]
@all-contributors please add @Sab94 for code and design

**Comment by asabya** [comment]
@yannbf Thanks for taking the time to merge it. After this pr ionic released v4 and I stopped working on ionic3 as well as ionic and moved on. Anyway I think this will help others in need.

**Comment by yannbf** [comment]
> @yannbf Thanks for taking the time to merge it. After this pr ionic released v4 and I stopped working on ionic3 as well as ionic and moved on. Anyway I think this will help others in need.

Indeed! Moving from ionic 3 to 4 in this repo is quite an effort, and given that I am not currently focusing on ionic, I am planning just to park it the way it is, as it can be helpful indeed to people who are using Ionic 3.

**Pull request merged**
